### ISSUE TITLE
the example got the errors

### ISSUE THREAD

**Issue by JohnHour89** [garrettmac/react-native-pagination#2]
Hi, I was able to run your project but I found only the Horizontal Paged Example was able to run whereas the others returned this error, may I know can you solve it? Thank you.

![image](https://user-images.githubusercontent.com/19371443/30526668-57ccd0a2-9c51-11e7-86a1-15d077a9e2d7.png)

**Comment by garrettmac** [comment]
thanks, ok ill take a look

**Comment by ahikmatf** [comment]
any update on this?

**Comment by zokypesch** [comment]
anybody get update ??

**Comment by gkgkska** [comment]
who got the update ??

**Comment by garrettmac** [comment]
should be resolved now!
