### ISSUE TITLE
PropTypes instead propTypes error

### ISSUE THREAD

**Issue by angelmaturanat** [garrettmac/react-native-pagination#4]
Hi everyone, i have a problem in render view with react native pagination!

<img width="317" alt="captura de pantalla 2018-01-25 a la s 10 00 44" src="https://user-images.githubusercontent.com/23390169/35389507-b6e3fd34-01b6-11e8-809f-2dec67e6142e.png">

<img width="1440" alt="captura de pantalla 2018-01-25 a la s 10 01 46" src="https://user-images.githubusercontent.com/23390169/35389527-ca9e5766-01b6-11e8-85cb-4df721c393ff.png">

**When i remove the pagination code this error disappears.**

I have not found information about it, I hope you could help me (sorry for my english).

**Comment by garrettmac** [comment]
fixed.
