### ISSUE TITLE
Changing onViewableItemsChanged on the fly is not supported

### ISSUE THREAD

**Issue by lucaszanella** [garrettmac/react-native-pagination#5]
I'm testing the example on the readme, this is what I get:

Changing onViewableItemsChanged on the fly is not supported
https://imgur.com/a/02qPbCE

I see that the line

```
  // REQUIRED for ReactNativePagination to work correctly
  onViewableItemsChanged = ({ viewableItems, changed }) =>
    this.setState({ viewableItems });
```

Tells that this is crucial but how if it breaks everything? Did something change in newer versions?

**Comment by lucaszanella** [comment]
Changing

`          onViewableItemsChanged={this.onViewableItemsChanged.bind(this)} //need this`

to 

`          onViewableItemsChanged={this.onViewableItemsChanged} //need this`

works but I don't know if it's supposed to be like this. I just saw at https://github.com/facebook/react-native/issues/17408 that no bind was needed.

I'm still getting the prop types error as reported by another user here, and this one:

https://imgur.com/a/P0bhUyr

don't know if it's related to this one but I'm going to investigate

**Comment by cyphire** [comment]
Am i missing something? Post your code.  I just had a problem where I was using a number as my key property and I had to change it to a string.  I'll bet thats the problem you guys are having.

**Comment by garrettmac** [comment]
fixed

**Comment by skurgansky-sugarcrm** [comment]
what should i do if i intend to render FlatList in function component with hooks ? I can't have methods or bind there.. and i can't useCallback because my onViewableItemsChanged depends on state values

**Comment by jan-miksik** [comment]
For me worked this https://stackoverflow.com/questions/48045696/flatlist-scrollview-error-on-any-state-change-invariant-violation-changing-on/57502343#_=_

**Comment by Soto92** [comment]
@jan-miksik it worked for me too
thank u

**Comment by JordiParraCrespo** [comment]
This worked for me:
`   const onViewRef = useRef((info: { viewableItems: ViewToken[]; changed: ViewToken[] }) => {
        setActiveIndex(info.viewableItems[0].index || 0);
    });`

`onViewableItemsChanged={onViewRef.current}`
